feat(cjs): allow users to wrap requireModule calls
wixplosives/file-services pull request #619
Opened 2022-03-17 08:13 UTC by RomanYarik

Currently the users has no ability to know when a require call started or finished.

We want to allow the users the ability to hook into the evaluation process.

2022-03-17 08:48 UTC, barak007 requested changes
You must add more test cases to ensure the right behavior. Like deeper nesting. multiple times same module evaluation. Multiple requests that resolves to the same module. My debate is to maybe wrap the eval instead of the require. or add the cache to the wrap function that way you will be able to distinguish if the module is fresh without external registry. But maybe it's not needed. This is why more tests are needed.

2022-03-21 17:50 UTC, barak007 reviewed
Generally looks good did the minimum modification to the core module system. And the wrapped one gives the most capabilities.

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/managed-cjs-module-system.ts
> +          if (!moduleGraph.has(modulePath)) {
Combine ifs

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/managed-cjs-module-system.ts
> +  const invalidateModule = (modulePath: string | false, visited = new Set<string>()) => {
Maybe we need pass filter here. Let's talk about it

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/managed-cjs-module-system.ts
> +  const invalidateModule = (modulePath: string | false, visited = new Set<string>()) => {
Or even the strategy

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/managed-cjs-module-system.ts
> +  const moduleGraph = new Map<
Let's think if we can expose the module graph

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/base-cjs-module-system.ts
> +  const wrappedRequireModule = wrapRequire(requireModule, loadedModules);
We don't want to wrap if we don't need it's just en extra function call and worth the less nice code

2022-03-21 17:50 UTC, barak007 commented on packages/commonjs/src/managed-cjs-module-system.ts
> +    resolveFrom: (contextPath, request, origin) => {
We might want to expose resolveThrow

2022-03-23 13:48 UTC, barak007 commented on packages/commonjs/src/base-cjs-module-system.ts
> +        newModule.children.push(loadedModule);
Chack if in node they appear twice

2022-03-24 17:08 UTC, RomanYarik commented
re-implemented at #621

2022-03-24 17:08 UTC, closed without merging